### ISSUE TITLE
How to input paired design

### ISSUE THREAD

**Issue by MingL196** [jeffbhasin/methylaction#3]
I currently have a paired-design dataset, where there are 
38 samples, 
19 of which are cases, 19 of which are controls
consisting of 19 pairs of twins. 

The paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4705678/ claims that it supports paired design. However, I can't seem to find where to input the sample pairing data.

How do I input both the pair data and case/control data in methylaction?

Thanks,
Ming

**Comment by jeffbhasin** [comment]
Hello Ming,
You can indeed do a paired-subjects dataset using MethylAction as we mentioned in the paper. The approach is to add a column that indicates pair membership to the CSV file that you read in using readSampleInfo(). You could call this column something like "paired_subject". So for example the first sample would indicate "Sample 1" for both the case and control sample row in the samplesheet for this "paired_subject" column, and so on for each of the 19 samples. The value should be identical for both members in the pair. Then, when you call methylaction(), set the name of this column in the adjust.var argument (i.e. adjust.var="paired_subject" or whatever you choose to name this column).

Jeff

**Comment by MingL196** [comment]
Hi, 

I am a bit confused about using adjust.var to specify a paired design experiment.

In our experiment, we have 19 case-control pairs. Each case control pair has similar ages. For example:

paired_subject | sample | group (case/control) 
------ | -- | ---- 
1 | 1001 | 1 
1 | 1002 | 0 
2 | 1003 | 1 
2 | 1004 | 0 

We would like to set up pairwise comparisons:

subject_1 | sample_1 | group_1 | compare_to | subject_2 | sample_2 | group_2
------ | -- | ---- | --- | ------ | -- | ---- 
1 | 1001 | 1 | <-> | 1 | 1002 | 0 
2 | 1003 | 1 | <-> | 2 | 1004 | 0 

You recommended that I add the pair variable by using the option adjust.var="paired_subject".

In your paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4705678/ , you wrote that:
"In MethylAction, the first stage performs the negative binomial test from DESeq (33) for each pairwise comparison." 

However, your first stage function (analysis.r, line 72) doesn't use the variable adjust.var at all, and as such wouldn't have the pair data to perform pairwise comparisons. In fact, adjust.var seems to only be used as a covariate in stage 2 testing.

1. Is adjust.var using the "paired_subject" variable as covariate or as pairing data?
I.e. in mixed model terms, is adjust.var specifying a fixed effect or a random effect?

2. How does Methylaction distinguish between covariate and pairing data?

--------------------------------------

By the way, should the variable
`counts`
in lines 508-513 of analysis.r be
`counts[rows,,drop=F]`
?

--------------------------------------
